### ISSUE TITLE
Having a problem with #f28281

### ISSUE THREAD

**Issue by prewk** [radubrehar/react-color-picker#3]
Hi, when i use `#f28281` as `defaultValue` in an uncontrolled component the color picker initialises like this:
![screenshot 2015-02-18 10 29 30](https://cloud.githubusercontent.com/assets/640102/6244885/138f9eea-b759-11e4-9e3f-88cff5fc8d71.png)

Note how the hue spectrum bar has the right color (red), but the saturation spectrum is blue. Clicking the saturation spectrum callbacks with a blue color, clicking the hue spectrum callbacks with the correct (pink) color.

**Comment by radubrehar** [comment]
Very interesting bug and very good catch! Thanks a lot! Please update to v 2.1.5, published to npm.

**Comment by prewk** [comment]
Great, thanks :)
